// <auto-generated />
using System;
using CommunityBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunityBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916125215_AddDurableActivities")]
    partial class AddDurableActivities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunityBot.Core.Activities.ActivityCaptureGate", b =>
                {
                    b.Property<string>("EventType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.HasKey("EventType")
                        .HasName("pk_activity_capture_gates");

                    b.ToTable("activity_capture_gates", (string)null);

                    b.HasData(
                        new
                        {
                            EventType = "ShopPurchaseCompleted"
                        });
                });

            modelBuilder.Entity("CommunityBot.Core.Activities.ActivityConsumption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_event_id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<long>("SubscriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subscription_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_activity_consumptions");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_activity_consumptions_subscription_id");

                    b.HasIndex("ActivityEventId", "SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_activity_consumptions_event_subscription");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_activity_consumptions_pending_queue")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("activity_consumptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_activity_consumptions_attempt_count_non_negative", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("CommunityBot.Core.Activities.ActivityEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer")
                        .HasColumnName("contract_version");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_count");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("source_reference");

                    b.HasKey("Id")
                        .HasName("pk_activity_events");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_activity_events_event_id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_activity_events_event_type");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_activity_events_member_id");

                    b.ToTable("activity_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_activity_events_contract_version_positive", "contract_version > 0");

                            t.HasCheckConstraint("CK_activity_events_event_id_not_empty", "event_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_activity_events_occurrence_count_positive", "occurrence_count > 0");

                            t.HasCheckConstraint("CK_activity_events_source_reference_not_blank", "source_reference IS NULL OR length(btrim(source_reference)) > 0");
                        });
                });

            modelBuilder.Entity("CommunityBot.Core.Activities.ActivitySubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CaptureFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capture_from");

                    b.Property<DateTime>("CaptureUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capture_until");

                    b.Property<string>("ConsumerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consumer_type");

                    b.Property<string>("ContextReference")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("context_reference");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_activity_subscriptions");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_activity_subscriptions_event_type");

                    b.HasIndex("ConsumerType", "ContextReference", "EventType")
                        .IsUnique()
                        .HasDatabaseName("ux_activity_subscriptions_consumer_context_event_type");

                    b.ToTable("activity_subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_activity_subscriptions_context_reference_not_blank", "length(btrim(context_reference)) > 0");

                            t.HasCheckConstraint("CK_activity_subscriptions_valid_window", "capture_until > capture_from");
                        });
                });

            modelBuilder.Entity("CommunityBot.Core.Economy.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_transactions_member_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("CommunityBot.Core.Items.InventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_id");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inventories");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_inventories_item_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_inventories_member_id");

                    b.HasIndex("MemberId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_inventories_member_item_active")
                        .HasFilter("status = 'Active'");

                    b.ToTable("inventories", null, t =>
                        {
                            t.HasCheckConstraint("CK_inventories_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("CommunityBot.Core.Items.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GrantedRoleKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("granted_role_key");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stackable");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("CommunityBot.Core.Items.ShopItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shop_items");

                    b.ToTable("shop_items", (string)null);
                });

            modelBuilder.Entity("CommunityBot.Core.Members.Member", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrencyBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("currency_balance");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bot");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("CommunityBot.Core.Rewards.RewardEntitlement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("RewardReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reward_reference");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reward_type");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reward_entitlements");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_reward_entitlements_member_id");

                    b.HasIndex("SourceReference")
                        .HasDatabaseName("ix_reward_entitlements_source_reference");

                    b.ToTable("reward_entitlements", null, t =>
                        {
                            t.HasCheckConstraint("CK_reward_entitlements_attempt_count_non_negative", "attempt_count >= 0");

                            t.HasCheckConstraint("CK_reward_entitlements_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("CommunityBot.Core.Activities.ActivityConsumption", b =>
                {
                    b.HasOne("CommunityBot.Core.Activities.ActivityEvent", "ActivityEvent")
                        .WithMany()
                        .HasForeignKey("ActivityEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_consumptions_activity_events_activity_event_id");

                    b.HasOne("CommunityBot.Core.Activities.ActivitySubscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_consumptions_activity_subscriptions_subscription_id");

                    b.Navigation("ActivityEvent");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("CommunityBot.Core.Activities.ActivityEvent", b =>
                {
                    b.HasOne("CommunityBot.Core.Activities.ActivityCaptureGate", null)
                        .WithMany()
                        .HasForeignKey("EventType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_events_activity_capture_gates_event_type");

                    b.HasOne("CommunityBot.Core.Members.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_events_members_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CommunityBot.Core.Activities.ActivitySubscription", b =>
                {
                    b.HasOne("CommunityBot.Core.Activities.ActivityCaptureGate", "CaptureGate")
                        .WithMany()
                        .HasForeignKey("EventType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_subscriptions_activity_capture_gates_event_type");

                    b.Navigation("CaptureGate");
                });

            modelBuilder.Entity("CommunityBot.Core.Economy.Transaction", b =>
                {
                    b.HasOne("CommunityBot.Core.Members.Member", "Member")
                        .WithMany("Transactions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_members_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CommunityBot.Core.Items.InventoryItem", b =>
                {
                    b.HasOne("CommunityBot.Core.Items.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_items_item_id");

                    b.HasOne("CommunityBot.Core.Members.Member", "Member")
                        .WithMany("Inventory")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_members_member_id");

                    b.Navigation("Item");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CommunityBot.Core.Items.ShopItem", b =>
                {
                    b.HasOne("CommunityBot.Core.Items.Item", "Item")
                        .WithOne()
                        .HasForeignKey("CommunityBot.Core.Items.ShopItem", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shop_items_items_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CommunityBot.Core.Rewards.RewardEntitlement", b =>
                {
                    b.HasOne("CommunityBot.Core.Members.Member", "Member")
                        .WithMany("RewardEntitlements")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reward_entitlements_members_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CommunityBot.Core.Members.Member", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("RewardEntitlements");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
